In [1]:
#Q1
X = [[12,7,3],
     [4 ,5,6],
     [7 ,8,9]]
Y = [[5,8,1],
     [6,7,3], 
     [4,5,9]]

result = [[0,0,0], 
          [0,0,0], 
          [0,0,0]]

for i in range(len(X)): 
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j] 
            
for r in result: 
    print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [2]:
#Q2
X = [[12,7,3],
     [4 ,5,6],
     [7 ,8,9]]
Y = [[5,8,1],
     [6,7,3], 
     [4,5,9]]

result = [[0,0,0], 
          [0,0,0], 
          [0,0,0]]

for i in range(len(X)): 
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j] 
            
for r in result: 
    print(r)


[114, 160, 60]
[74, 97, 73]
[119, 157, 112]


In [3]:
#Q3
X = [[12,7,3],
     [4 ,5,6],
     [7 ,8,9]]
Y = [[5,8,1],
     [6,7,3], 
     [4,5,9]]

result = [[0,0,0], 
          [0,0,0], 
          [0,0,0]]

for i in range(len(X)): 
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j] 
            
for r in result: 
    print(r)


[114, 160, 60]
[74, 97, 73]
[119, 157, 112]


In [4]:
#Q4
import numpy as np
X = [[12,7,3],
     [4 ,5,6],
     [7 ,8,9]]
Y = [[5,8,1],
     [6,7,3], 
     [4,5,9]]
print("addition of two Matrix:")
print(np.add(X,Y))

print("Subtraction of two Matrix:")
print(np.subtract(X,Y))

addition of two Matrix:
[[17 15  4]
 [10 12  9]
 [11 13 18]]
Subtraction of two Matrix:
[[ 7 -1  2]
 [-2 -2  3]
 [ 3  3  0]]


In [5]:
#Q5
import numpy as np
matrix = [[1,2,3],
          [4,5,6]]
print(matrix)
print("\n")
print(np.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


In [6]:
#Q6
N =4 
print("The Dimension:" +str(N))
res = [list(range(1 + N * i,1+ N * (i + 1)))
       for i in range(N)]

print("The created matrix of N * N: " + str(res))

The Dimension:4
The created matrix of N * N: [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [7]:
#Q7
test_list = [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
print("The original list is : " + str(test_list)) 
K = 2

res = [sub[K] for sub in test_list] 

print("The Kth column of Matrix is :" + str(res))


The original list is : [[4, 5, 6], [8, 1, 10], [7, 12, 5]]
The Kth column of Matrix is :[6, 10, 5]


In [8]:
#Q8
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
print("The original list : " + str(test_list)) 


res = [] 
N = 0 

while N != len(test_list): 
    temp = '' 
    for idx in test_list:
        try: temp = temp + idx[N] 
        except IndexError: pass 
    res.append(temp) 
    N = N + 1 

res = [ele for ele in res if ele] 

print("List after column Concatenation : " + str(res)) 

The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['GfgisBest', 'goodfor']


In [9]:
#Q9
def  isPalindrome(s):
    return s == s[::-1]

s = "malayalam"
ans = isPalindrome(s)

if ans:
    print("Yes")
else:
    print("No")
    

Yes


In [10]:
#Q10
string = 'amaama' 
half = int(len(string) / 2) 
if len(string) % 2 == 0:
    first_str = string[:half]
    second_str = string[half:]
else:
    first_str= string[:half]
    second_str= string[half+1:]

#symetric
if first_str == second_str:
    print(string, 'string is symmertical')
else:
    print(string, 'string is not symmertical')
if first_str == second_str[::-1]:
    print(string, 'string is palindrome') 
else: 
    print(string, 'string is not palindrome') 

amaama string is symmertical
amaama string is palindrome
